name: sample_dart
description: A sample command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter_project_generator:
    path: /Users/lenguyenkhoa/Documents/GitHub/flutter_project_template_generator/flutter_project_generator

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
