name: flutter_project_generator
description: Easily generate your flutter project with configs file
version: 1.0.0+1
homepage: https://github.com/ankiimation/flutter_project_template_generator

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0
dependencies: 
  yaml: ^3.1.1
  yaml_edit: ^2.1.0
